[package]
name = "lld-wrapper"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
libwild = { git = "https://github.com/davidlattimore/wild.git", rev = "e046ec6", features = [
    "fork",
] }
